### ISSUE TITLE
Add rakinepalli's Home Town Tips

### ISSUE THREAD

**Issue by rakinepalli** [githubteacher/developers-jan-16#13]
### Task List
- [x] Create a branch
- [x] Add my file
- [x] Create a pull request
- [x] Discuss
- [x] Merge pull request
# Places to eat:
- [x] Gokul Chat
- [x] Rayalaseema ruchulu

**Comment by kishorebolinidi** [comment]
100% complete :dango:
