### ISSUE TITLE
Add GitHubTeacher's Home Town Tips

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/developers-jan-16#2]
## Fuquay Varina, NC
- Places to eat
- Fun things to do
- Things to avoid
### Task List
- [x] Create a branch
- [x] Add my file
- [x] Create a pull request
- [ ] Discuss
- [ ] Merge pull request
